apiVersion: v1
kind: Service
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app: mme
  name: mme
spec:
  clusterIP: 172.30.0.9
  ports:
    - name: "3868"
      port: 3868
      protocol: UDP
      targetPort: 3868
    - name: 3868-tcp
      port: 3868
      targetPort: 3868
    - name: 3868-sctp
      port: 3868
      protocol: SCTP
      targetPort: 3868
    - name: "5868"
      port: 5868
      protocol: UDP
      targetPort: 5868
    - name: 5868-tcp
      port: 5868
      targetPort: 5868
    - name: 5868-sctp
      port: 5868
      protocol: SCTP
      targetPort: 5868
    - name: "36412"
      port: 36412
      protocol: SCTP
      targetPort: 36412
    - name: "2123"
      port: 2123
      protocol: UDP
      targetPort: 2123
  selector:
    app: mme
status:
  loadBalancer: {}
