apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rtpengine
  name: rtpengine
spec:
  clusterIP: 172.30.0.16
  ports:
    - name: "2223"
      port: 2223
      protocol: UDP
      targetPort: 2223
    - name: "0"
      port: 0
      protocol: UDP
      targetPort: 0
  selector:
    app: rtpengine
status:
  loadBalancer: {}
