apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dns
  name: dns
spec:
  ports:
    - name: "53"
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: dns
status:
  loadBalancer: {}
