apiVersion: v1
kind: Service
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    io.kompose.service: hss
  name: hss
spec:
  clusterIP: 172.30.0.3
  externalIP: 192.168.20.175
  ports:
    - name: "3868"
      port: 3868
      protocol: UDP
      targetPort: 3868
    - name: 3868-tcp
      port: 3868
      targetPort: 3868
    - name: 3868-sctp
      port: 3868
      protocol: SCTP
      targetPort: 3868
    - name: "5868"
      port: 5868
      protocol: UDP
      targetPort: 5868
    - name: 5868-tcp
      port: 5868
      targetPort: 5868
    - name: 5868-sctp
      port: 5868
      protocol: SCTP
      targetPort: 5868
  selector:
    io.kompose.service: hss
status:
  loadBalancer: {}
