apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fhoss
  name: fhoss
spec:
  clusterIP: 172.30.0.18
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "3868"
      port: 3868
      protocol: UDP
      targetPort: 3868
    - name: 3868-tcp
      port: 3868
      targetPort: 3868
  selector:
    app: fhoss
status:
  loadBalancer: {}
