apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  labels:
    app: webui
spec:
  type: ClusterIP
  #clusterIP: 172.30.0.25
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: webui