apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: smf
  name: smf
spec:
  clusterIP: 172.30.0.7
  ports:
    - name: "3868"
      port: 3868
      protocol: UDP
      targetPort: 3868
    - name: 3868-tcp
      port: 3868
      targetPort: 3868
    - name: 3868-sctp
      port: 3868
      protocol: SCTP
      targetPort: 3868
    - name: "5868"
      port: 5868
      protocol: UDP
      targetPort: 5868
    - name: 5868-tcp
      port: 5868
      targetPort: 5868
    - name: 5868-sctp
      port: 5868
      protocol: SCTP
      targetPort: 5868
    - name: "8805"
      port: 8805
      protocol: UDP
      targetPort: 8805
    - name: "2123"
      port: 2123
      protocol: UDP
      targetPort: 2123
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    app: smf
status:
  loadBalancer: {}
