apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
spec:
  clusterIP: 172.30.0.2
  ports:
    - name: "27017"
      port: 27017
      protocol: UDP
      targetPort: 27017
    - name: 27017-tcp
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
status:
  loadBalancer: {}
