apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sgwc
  name: sgwc
spec:
  clusterIP: 172.30.0.5
  ports:
    - name: "2123"
      port: 2123
      protocol: UDP
      targetPort: 2123
    - name: "8805"
      port: 8805
      protocol: UDP
      targetPort: 8805
  selector:
    app: sgwc
status:
  loadBalancer: {}
