apiVersion: v1
kind: Service
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app: sgwu
  name: sgwu
spec:
  clusterIP: 172.30.0.6
  ports:
    - name: "8805"
      port: 8805
      protocol: UDP
      targetPort: 8805
    - name: "2152"
      port: 2152
      protocol: UDP
      targetPort: 2152
  selector:
    app: sgwu
status:
  loadBalancer: {}
