apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: amf
  name: amf
spec:
  ports:
    - name: "38412"
      port: 38412
      protocol: SCTP
      targetPort: 38412
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    io.kompose.service: amf
status:
  loadBalancer: {}
