apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: upf
  name: upf
spec:
  clusterIP: 172.30.0.8
  ports:
    - name: "2152"
      port: 2152
      protocol: UDP
      targetPort: 2152
    - name: "8805"
      port: 8805
      protocol: UDP
      targetPort: 8805
  selector:
    app: upf
status:
  loadBalancer: {}
