apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: scscf
  name: scscf
spec:
  clusterIP: 172.30.0.20
  ports:
    - name: "3870"
      port: 3870
      protocol: UDP
      targetPort: 3870
    - name: 3870-tcp
      port: 3870
      targetPort: 3870
    - name: "6060"
      port: 6060
      protocol: UDP
      targetPort: 6060
    - name: 6060-tcp
      port: 6060
      targetPort: 6060
  selector:
    app: scscf
status:
  loadBalancer: {}
